### ISSUE TITLE
[iOS] React Native 0.75.3 Crash on Opening Camera

### ISSUE THREAD

**Issue by ravindraguptacapgemini** [pushpender-singh-ap/react-native-scanner#29] opened 2024-10-23 18:37 UTC
### Current behaviour

I have recently upgraded app to 0.75.3, and the App has started crashing on camera open

### Expected behaviour
App should work fine without any crash and scan codes

### How to reproduce?
Just try to open camera for code scan

### Preview
<img width="1475" alt="Screenshot 2024-10-24 at 12 04 48 AM" src="https://github.com/user-attachments/assets/11d1abcd-9ef6-48fa-b093-063581826bcf">

### What have you tried so far?
Tried debugging the issue on Xcode, not able to get a clear root cause

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | 15.2
| android                        | x
| react-native                | 0.75.3
| @pushpendersingh/react-native-scanner    | 1.2.0
| node                            | 18.17.1
| yarn                | 1.22.19

**Comment by pushpender-singh-ap** [comment] 2024-10-23 18:52
Hi @ravindraguptacapgemini, Can you provide a minimal repro which demonstrates the issue?

**Comment by pushpender-singh-ap** [comment] 2024-10-23 21:04
Hi @ravindraguptacapgemini 

Thank you for bringing up the issue. I have tested the `@pushpendersingh/react-native-scanner` library on both React Native versions `0.75.3` and `0.76.0`. After thorough debugging, I can confirm that the library is functioning as expected without any issues in these versions.

If you'd like to test it yourself, please try the example provided in the `example` folder. The example has been upgraded to React Native 0.76.0 and is working fine. If you need to test the library on version 0.75.3, you can find the relevant example in the `example/0.75.3` branch.

Please feel free to reach out if you have any further questions or need additional assistance. For now, I am closing this issue.

Best regards,
Pushpender Singh

**Closed by pushpender-singh-ap** 2024-10-23 21:04 UTC
Labels: bug

**Comment by ravindraguptacapgemini** [comment] 2024-10-24 03:05
@pushpender-singh-ap okay let me check it again, I have few more changes in my local repo.
Can you please let me know, why we need to use Command
`Commands.releaseCamera(cameraRef.current);`
rather calling the methods directly on the ref
`cameraRef.current.releaseCamera();`

**Comment by pushpender-singh-ap** [comment] 2024-10-24 10:45
Hi @ravindraguptacapgemini 

It’s essential to use `Commands.releaseCamera(cameraRef.current)` instead of calling `cameraRef.current.releaseCamera() `directly because the `Commands` object utilizes React Native's code generation system for native commands. This approach ensures that the command is dispatched correctly to the native layer, maintaining proper interaction between the JavaScript and native modules.

**Comment by ravindraguptacapgemini** [comment] 2024-10-24 12:00
@pushpender-singh-ap there is a definite crash when opening camera. 
I have found it that it's happening due to the `API Validation` under diagnostics settings in scheme
<img width="686" alt="Screenshot 2024-10-24 at 5 26 49 PM" src="https://github.com/user-attachments/assets/5d31205c-99c3-4168-82ff-d9b8b04fb846">

Currently, after disabling this option prevents crash. So we have a workaround but I am not sure what will be the impacts after disabling this option.

**Comment by pushpender-singh-ap** [comment] 2024-10-24 12:15
Hi @ravindraguptacapgemini 

Thank you for the update. I'm not sure why you're experiencing this issue, as everything works fine on my end. I’ve tested the library in both React Native versions 0.75.3 and 0.76, with the `API Validation` enabled, and I haven’t encountered any crashes.

Have you had a chance to test the example provided in the `example` folder? It could help identify if the issue is specific to your project setup.

Please let me know if you need further assistance or guidance in troubleshooting this.

Best regards,
Pushpender Singh

<img width="734" alt="Screenshot 2024-10-24 at 5 44 28 PM" src="https://github.com/user-attachments/assets/5078809a-ed4d-44c4-9068-19f134b7068e">
